### ISSUE TITLE
Audit Request Counter

### ISSUE THREAD

**Issue by tylerferrara** [kubernetes-sigs/promo-tools#358]
#### What would you like to be added:
Enable a simple request counter when the user passes the `--verbose` flag. This counter should increment each time the auditor makes an HTTP request to GCR. Every 10min period, the number of queries should printed to logs and reset the counter back to zero. This effectively measures the network performance of the auditor in the same way the Container Registry measures it's [quota](https://cloud.google.com/container-registry/quotas): 50,000 HTTP requests every 10 minutes.

**Requirements:**

- [x] Create a simple request counter #359
- [x] Concurrently log the counter at 10min intervals #363 
- [x] Create multiple counters that log at different offsets #364 #383
- [x] Allow for non-resettable request counters #382 
- [x] Create warning if queries exceed the GCR quota #384
- [x] Test the Log function with fake time #370 #371 #376 #377 
- [x] Enable this feature for all audit builds #367 #381 
- [ ] Allow for gracefully termination
- [ ] Create a quota structure that uses a sliding window

#### Why is this needed:
The auditor makes many requests to GCR in order to validate children of manifest.lists. This is currently handled by requesting all images within the project:`k8s-artifacts-prod` which is a known bottleneck #259.

Additionally, the way in which we request GCR is via simple HTTP requests which are not tracked by the Container Registry API  #353. Therefore, gaining visibility into the number of requests the auditor is making while running can help diagnose throttling. This behavior often causes a backup of unacknowledged Pub/Sub messages, resulting in unwanted alerts [#2364](https://github.com/kubernetes/k8s.io/issues/2364).

cc: @listx @amwat @justaugustus @kubernetes-sigs/release-engineering
