### ISSUE TITLE
[Umbrella] Enable automated file promotion

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/promo-tools#413]
#### What would you like to be added:

(Filing this to capture comments/progress https://github.com/kubernetes/k8s.io/issues/2624, some notes that I was scribbling locally, and some of the discussion I had with @justinsb a little earlier today.)

### Restrictions

- [x] `kpromo` should always use service account / implicit credentials: https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/412
- [ ] Validate auth before starting ops
- [ ] Validate directory structure / destinations before promotion
- [ ] Block top-level promotions
- [ ] Ensure promoted artifacts go to `k8s-artifacts-prod/binaries/<project>`

#### Service accounts

- [x] Create separate service account for file promotion: https://github.com/kubernetes/k8s.io/pull/2700
- [x] Utilize new service account in Prow jobs: https://github.com/kubernetes/test-infra/pull/23557
- [x] Update existing manifests to use new service account: https://github.com/kubernetes/k8s.io/pull/2704
- [ ] Can we support top-level service accounts (instead of within `filestore`)
- [ ] Do we need a `k8s-infra-promoter-bak` account that can write to `k8s-artifacts-prod-bak`? (ref: https://github.com/kubernetes/k8s.io/pull/2700#discussion_r706470971)

#### From https://github.com/kubernetes/k8s.io/issues/2624#issuecomment-909858376:

- Enable manifests with artifacts that no longer exist on staging buckets to be skipped (we expect the staging artifacts to age out)
  - We should still report the issue, and:
  - Probably still call this a failure if any of the assets in a single manifest are not found i.e., if there were supposed to be 10 files in a 1.16 release but we only find 1, the copy should be skipped and reported on
- Should we allow backfill operations on a directory i.e., if the staging directory initially had 10 objects, but now has 15, do we care that 5 objects will be promoted on the next run?
  - Should this be configurable per project?

### Later

- [x] Update golangci-lint + re-lint: https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/416
- [ ] Improve command ergonomics
- [ ] e2es for file promotion
- [ ] Integrate CIP into kpromo

### Done

- [x] `kpromo` image build pre- and postsubmit: https://github.com/kubernetes/test-infra/pull/23416
- [x] Image building init for `kpromo`: https://github.com/kubernetes/release/pull/2231
- [x] Test file promotion periodic job: https://github.com/kubernetes/test-infra/pull/23417
- [x] Break dependencies on packages in k/release:
  - [x] Init object and gcli packages from k/release: https://github.com/kubernetes-sigs/release-sdk/pull/2
  - [x] Migrate `pkg/object` and `pkg/gcp/gcp.go` to sigs.k8s.io/release-sdk: https://github.com/kubernetes/release/pull/2232
- [x] Migrate kpromo/cip-mm tools/packages into repo:
  - [x] https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/407
  - [x] https://github.com/kubernetes/release/pull/2240
- [x] Tidy image building configs
  - [x] https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/408
  - [x] https://github.com/kubernetes/test-infra/pull/23430
- [x] Support directory traversal for file promotion: https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/409
- [x] Support for multiple manifests (all staging projects) and multiple releases (per project): https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/409
- [x] Validate filestore directory matches files directory: https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/409
- [x] Update to go1.17: https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/409

Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1630416874004700
/assign
cc: @ameukam @spiffxp @kubernetes-sigs/release-engineering 
/area artifacts
