### ISSUE TITLE
v3.3.0: Release tracking

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/promo-tools#430]
#### What would you like to be added:

Tracking some cleanup tasks we'll want to get into the next release...

#### Why is this needed:

- [x] Update docs to reflect new branch references: https://github.com/kubernetes-sigs/promo-tools/pull/429
- [x] Clean up dead links: https://github.com/kubernetes-sigs/promo-tools/pull/428
- [x] (optional) Unify image building make targets: https://github.com/kubernetes-sigs/promo-tools/pull/434

---

**NO LONGER REQUIRED -- Allow imports again**

(Cut a v3.2.1 which fixes this: https://github.com/kubernetes-sigs/promo-tools/releases/tag/v3.2.1)

Following the repo rename in https://github.com/kubernetes-sigs/promo-tools/issues/424, I wanted to importing the new module in k/release and 👇🏾:

```console
❯ go mod tidy
go: finding module for package sigs.k8s.io/promo-tools/v3/legacy/dockerregistry
go: downloading sigs.k8s.io/promo-tools v1.339.0
go: downloading sigs.k8s.io/promo-tools/v3 v3.2.0
go: found sigs.k8s.io/promo-tools/v3/legacy/dockerregistry in sigs.k8s.io/promo-tools/v3 v3.2.0
go: k8s.io/release/cmd/krel/cmd imports
	sigs.k8s.io/promo-tools/v3/legacy/dockerregistry: sigs.k8s.io/promo-tools/v3@v3.2.0: parsing go.mod:
	module declares its path as: sigs.k8s.io/k8s-container-image-promoter/v3
	        but was required as: sigs.k8s.io/promo-tools/v3

❯ go get sigs.k8s.io/promo-tools/v3@v3.2.0
go get: sigs.k8s.io/promo-tools/v3@v3.2.0: parsing go.mod:
	module declares its path as: sigs.k8s.io/k8s-container-image-promoter/v3
	        but was required as: sigs.k8s.io/promo-tools/v3
```

I'm really hoping this will be tolerant of a new minor release and not require a v4 module to overcome...

/assign 
cc: @kubernetes-sigs/release-engineering

**Comment by justaugustus** [comment]
Release: https://github.com/kubernetes-sigs/promo-tools/releases/tag/v3.3.0
